### PR TITLE
Add details on background jobs

### PR DESCRIPTION
**Pull request by Cruikshanks**
https://eaflood.atlassian.net/browse/WATER-4270

Anyone working with the service will soon come across 'jobs' in all their various forms.

The ones that we want to have a grip on are those that run in the background, normally on a schedule, if only so that as we add our own we don't clash with them.

But for those new to the service, it would be handy to have some guidance on what 'jobs' means, the technologies used, and if we have details, what they are doing.

As we learn more, we'll try and keep this guidance updated. But for now, this adds guidance on the background jobs across the various apps (that we know of!)

### CODE REVIEW

**Comment by Cruikshanks** [comment]
Wrote this under the assumption that node-cron the package we use was interacting with crontab. It's not, scheduling is all done within the module (and therefore the app). It just uses crontab syntax for the scheduling.

So, just need to re-check the wording.

**Comment by Cruikshanks** [comment]
Only took a year and 4 months to complete! 😁

**Review by robertparkinson — APPROVED** [review]

**Comment by Cruikshanks** [comment]
Thanks @robertparkinson ! This is a reminder/update for old and new hands alike (@Demwunz @Jozzey @Beckyrose200 ). When it comes to changes in this repo we break with our convention of 'just-need-one-approval' is needed.

Because this repo is the source of the team's conventions and guidance we want everyone to at least acknowledge they have seen the changes.

So, before we merge anything ideally everyone has approved the change. If you're not able to or comfortable just a comment to acknowledge you have at least seen the change is also fine.

> This is not a 'hard' rule. If anyone is on leave or absent don't hang around until they are back! Think of it as a gift for them to look forward to! 😂

**Comment by Cruikshanks** [comment]
Merging anyway you monkeys as I need this to show off in our retro!

**Pull request merged**
